[tool.pytest.ini_options]
asyncio_mode = "auto"
filterwarnings = [
    "ignore::pydantic.warnings.PydanticDeprecationWarning:pyiceberg.*",
    "ignore:.*regex.*deprecated.*:fastapi.exceptions.FastAPIDeprecationWarning",
    "ignore::DeprecationWarning:pyiceberg.*",
    "ignore::DeprecationWarning:supabase.*",
    "ignore::DeprecationWarning:requests.*",
]
